# Taller: Introducción a Python
## Sesión: 02
## Econometrics Data Lab

### Carga de modulos o clases

In [3]:
# Estructura de llamado o carga de modulo 

# import nombre_modulo - Importar el modulo completo sin abreviatura 

import numpy

In [4]:
numpy.mean([10,20,30,40])

np.float64(25.0)

In [5]:
# import nombre_modulo as abreviatura - Importar el modulo completo con abreviatura 

import numpy as np

In [6]:
np.mean([10, 20, 30, 40])

np.float64(25.0)

In [7]:
# from nombre_modulo import clase/submodulo/herencia

from numpy import mean

In [8]:
mean([10, 20, 30, 40])

np.float64(25.0)

En ocasiones, hay modulos que contienen otros *submodulos* que a su vez dentro de cada *submodulo* hay diferentes *clases* (funciones), por lo tanto no se pueden llamar desde el modulo general, ejemplo:

In [18]:
import statsmodels.api as sm

In [19]:
sm.jarque_bera([10, 20, 30, 40])

AttributeError: module 'statsmodels.api' has no attribute 'jarque_bera'

Dentro de statsmodels (que esta abreviado como sm), sí existe la clase *jarque_bera* pero para ser usada hay llamar primero al submodulo de *stats* y de *statstools*, entonces quedaría de la siguiente manera:

In [20]:
# modulo.submodulo1.submodulo2.clase 
sm.stats.stattools.jarque_bera([10, 20, 30, 40])

(np.float64(0.3082666666666667),
 np.float64(0.8571577256951797),
 np.float64(0.0),
 np.float64(1.64))

In [22]:
# Llamando directamente a la clase 
from statsmodels.stats.stattools import jarque_bera

In [23]:
jarque_bera([10, 20, 30, 40])

(np.float64(0.3082666666666667),
 np.float64(0.8571577256951797),
 np.float64(0.0),
 np.float64(1.64))

### Tipos de datos

#### Numérico

In [25]:
# Número entero 

X = 20
X

20

In [26]:
type(X)

int

In [27]:
# Número racional, irracional 

X = 2.25
X

2.25

In [28]:
type(X)

float

In [29]:
X = 1.333333
X

1.333333

In [30]:
type(X)

float

In [46]:
X = -0.6666666
X

-0.6666666

In [32]:
type(X)

float

### Textuales (Cadenas de texto)

In [38]:
Nombre = 'Alexis'
Nombre

'Alexis'

In [39]:
type(Nombre)

str

### Valores lógicos o booleano

In [40]:
Check = True
Check

True

In [41]:
Check = False
Check

False

In [42]:
type(Check)

bool

In [47]:
X == 3

False

In [48]:
X = 3 

if X == 3:
    print("El valor de X es 3")
else:
    print("El valor de X no es 3")

El valor de X es 3

### Estructuras básicas

#### Variable

In [49]:
edad = 25
edad

25

In [50]:
promedio = np.mean([4, 6, 9, 10])
promedio

np.float64(7.25)

In [51]:
type(promedio)

numpy.float64

#### Lista

In [73]:
Edades = [24, 34, 40, 28, 27, 19, 20, 37]
Edades

[24, 34, 40, 28, 27, 19, 20, 37]

In [74]:
Edades[2]

40

In [75]:
Edades[2] = 38
Edades

[24, 34, 38, 28, 27, 19, 20, 37]

In [53]:
type(Edades)

list

In [54]:
Comics = ["Batman", "Superman", "Spider-man", "Wolverine"]
Comics

['Batman', 'Superman', 'Spider-man', 'Wolverine']

In [55]:
type(Comics)

list

In [56]:
Checks = [True, False, False, True, True]

In [57]:
Checks

[True, False, False, True, True]

In [58]:
type(Checks)

list

### Array

In [59]:
import numpy as np # Es necesario tener numpy cargado 

Edades = np.array([24, 34, 40, 28, 27, 19, 20, 37])
Edades

array([24, 34, 40, 28, 27, 19, 20, 37])

El objeto array permite realizar operaciones internas (desde el objeto) tales como: Suma, media, máximo, minimo, etc.

In [60]:
Edades.mean()

np.float64(28.625)

In [61]:
Edades.sum()

np.int64(229)

A diferencia de la lista que no define esos atributos dentro del obejeto.

In [62]:
Edades2 = [24, 34, 40, 28, 27, 19, 20, 37]
Edades2.mean()

AttributeError: 'list' object has no attribute 'mean'

In [64]:
# Elementos o atributos del array 

dir(Edades)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__xor__',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'device',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemsize',
 'mT',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'nonzero',
 'partition',
 'prod',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'to_device',
 'tobytes',
 'tofile',
 'tolist',
 'trace',
 'transpose',
 'var',
 'view']

#### Matrices con array

In [65]:
# Matriz de elementos 

Matriz = np.array(
    [
        [11, 21, 31], #Fila 1
        [21, 22, 23], #Fila 2
        [31, 32, 33], #Fila 3
    ]
)

Matriz

array([[11, 21, 31],
       [21, 22, 23],
       [31, 32, 33]])

In [66]:
Matriz.T

array([[11, 21, 31],
       [21, 22, 32],
       [31, 23, 33]])

In [67]:
Matriz.T * Matriz

array([[ 121,  441,  961],
       [ 441,  484,  736],
       [ 961,  736, 1089]])

In [71]:
# Inversa 
A = np.array(
    [
        [2, 5, 9], #Fila 1
        [11, 3, 7], #Fila 2
        [8, 4, 12], #Fila 3
    ]
)


np.linalg.inv(A)

array([[-0.04347826,  0.13043478, -0.04347826],
       [ 0.41304348,  0.26086957, -0.46195652],
       [-0.10869565, -0.17391304,  0.26630435]])

In [72]:
# Determinante 

np.linalg.det(A)

np.float64(-184.00000000000006)

### Diccionario

In [76]:
# Relación clave-valor 

persona = {
    "nombre": "Adonai",
    "edad": 34,
    "peso": 78
}

persona["nombre"]

'Adonai'

In [77]:
persona["edad"]

34

In [78]:
personas = {
    "nombres": ["Adonai", "Diana" , "Uriel", "Frank", "Daniel", "Alejandro", "Juan", "Mirko"],
    "edades": [34, 28, 30, 26, 30, 33, 26, 35],
    "pesos": [78, 60, 70, 80, 74, 82, 78, 79]
}

In [79]:
personas["nombres"]

['Adonai', 'Diana', 'Uriel', 'Frank', 'Daniel', 'Alejandro', 'Juan', 'Mirko']

### DataFrame

In [80]:
import pandas as pd

#### DataFrame mediante diccionarios

In [81]:
personas_df = pd.DataFrame(
    {
    "nombres": ["Adonai", "Diana" , "Uriel", "Frank", "Daniel", "Alejandro", "Juan", "Mirko"],
    "edades": [34, 28, 30, 26, 30, 33, 26, 35],
    "pesos": [78, 60, 70, 80, 74, 82, 78, 79]
    }
)

personas_df

     nombres  edades  pesos
0     Adonai      34     78
1      Diana      28     60
2      Uriel      30     70
3      Frank      26     80
4     Daniel      30     74
5  Alejandro      33     82
6       Juan      26     78
7      Mirko      35     79

In [82]:
personas_df = pd.DataFrame(
    {
    "nombres": ["Adonai", "Diana" , "Uriel", "Frank", "Daniel", "Alejandro", "Juan"],
    "edades": [34, 28, 30, 26, 30, 33, 26, 35],
    "pesos": [78, 60, 70, 80, 74, 82, 78, 79]
    }
)

personas_df

ValueError: All arrays must be of the same length

In [83]:
personas_df = pd.DataFrame(
    {
    "nombres": ["Adonai", "Diana" , "Uriel", "Frank", "Daniel", "Alejandro", "Juan", np.nan],
    "edades": [34, 28, 30, 26, 30, 33, 26, 35],
    "pesos": [78, 60, 70, 80, 74, 82, 78, 79]
    }
)

personas_df

     nombres  edades  pesos
0     Adonai      34     78
1      Diana      28     60
2      Uriel      30     70
3      Frank      26     80
4     Daniel      30     74
5  Alejandro      33     82
6       Juan      26     78
7        NaN      35     79

#### DataFrame paso a paso (columna por columna)

In [84]:
Personas_df = pd.DataFrame()
Personas_df["Nombres"] = ["Adonai", "Diana" , "Uriel", "Frank", "Daniel", "Alejandro", "Juan", "Mirko"]
Personas_df["Edades"] =  [34, 28, 30, 26, 30, 33, 26, 35]
Personas_df["Pesos"] = [78, 60, 70, 80, 74, 82, 78, 79]
Personas_df

     Nombres  Edades  Pesos
0     Adonai      34     78
1      Diana      28     60
2      Uriel      30     70
3      Frank      26     80
4     Daniel      30     74
5  Alejandro      33     82
6       Juan      26     78
7      Mirko      35     79